### ISSUE TITLE
Posted pictures are blurry

### ISSUE THREAD

**Issue by stodge** [lsnull/humhub-themes#1]
If I post a picture, the preview is blurry if I use the Nova theme.

**Comment by lsnull** [comment]
куда именно выкладываете , в комментарий или в публикацию и фотографию в редакторе или файлом ?

where it is laid out in a comment or in a publication and a photo editor or a file?

**Comment by stodge** [comment]
It's in a post that I submitted.

**Comment by stodge** [comment]
Did you manage to fix this?

**Comment by stodge** [comment]
I don't know if this is a good fix, but I commented out the width in theme.css at line 5246 in theme.css:

```
.post-files img {
    height: 100%!important;
    <!-- width: 100%!important; -->
    -webkit-animation-duration: 2s;
    animation-duration: 2s;
    object-fit: cover;
}
```

It means the preview pictures are much smaller, but at least I think they're no longer blurry.

Oh and you should also minimise the CSS files to reduce bandwidth.

**Comment by lsnull** [comment]
Ok!
file theme.css will be minimise
Fixed .post-files img
